apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: miloofcroton-io-tls
spec:
  secretName: miloofcroton-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: miloofcroton.io
  dnsNames:
    - miloofcroton.io
    - www.miloofcroton.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - miloofcroton.io
          - www.miloofcroton.io
